name: CI

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
      
      - name: yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build:production
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx --no-install semantic-release
