name: CI

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build:production
      - name: add changes
        run: git add --all
      - name: release
        run: npx semantic-release
